### ISSUE TITLE
Cannot run the latest v0.10.0-esp32-20210329 on Windows (OCD-327)

### ISSUE THREAD

**Issue by valeros** [espressif/openocd-esp32#151]
Hello, it seems that the latest release is broken on Windows for some reason:
![image](https://user-images.githubusercontent.com/886732/112982411-bf73fb00-915c-11eb-94e2-f48d6e796f2c.png)

**Comment by edbek** [comment]
Yes, I confirm, I have the same

**Comment by gerekon** [comment]
Hi @valeros ! 
Sorry for inconvenience. Since we added compressed uploads to flash openocd needs `zlib` now. Unfortunately we missed it in Windows release distro. We will fix it soon. As a temporary workaround if you have mingw32 installed you can run openocd from its shell or copy `libgcc_s_dw2-1.dll ` and `zlib1.dll ` to openocd bin dir.

**Comment by igrr** [comment]
Should be fixed by https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20210401.
