### ISSUE TITLE
[TW#18928] registerview in eclipse debugger (OCD-129)

### ISSUE THREAD

**Issue by igrr** [espressif/openocd-esp32#20]
_From @hackrid on September 16, 2017 18:5_

Hi,

hows your thinking regarding adding a register description file to embsysregview for esp8266 and esp32?
would improve the debugging expirience a lot. 

http://embsysregview.sourceforge.net/

best regards

_Copied from original issue: espressif/esp-idf#1007_

**Comment by igrr** [comment]
Thanks for the suggestion @hackrid, we will prepare the register description file.
I have moved the issue to openocd repository as it is more related to debugging features such as this one.

**Comment by hackrid** [comment]
thanks very much for picking this up! I appreciate it very much! keep us posted :)

**Comment by manoj153** [comment]
any update on when it's expected to release? I am finding ways how to debug esp32 with register and memory view

**Comment by gerekon** [comment]
Close this issue because it is unrelated to OpenOCD. Console GDB have all necessary means to check memory and registers. If you want to have it in IDE, please check ESP-IDF [VsCode extension](https://github.com/espressif/vscode-esp-idf-extension) (implements requested features) and (Eclipse plugin)[https://github.com/espressif/idf-eclipse-plugin]
