### ISSUE TITLE
[TW#20231] Uploading firmware to flash using GDB and OpenOCD

### ISSUE THREAD

**Issue by valeros** [espressif/openocd-esp32#32]
Hi guys, my question might not be related to OpenOCD itself (I would thankful if someone could point me out the right place for this issue), but I'm trying to upload firmware using GDB (`load` command with or without offset) but to no avail. All I get is:
```
"c:\Users\user\AppData\Local\Temp\arduino_build_140306\WiFiScan.ino.bin" is not an object file: File format not recognized
```
At the same time, direct uploading using the `program_esp32` command with OpenOCD works OK.
`mon program_esp32` in GDB also works.
Hardware: Olimex ARM USB OCD-H + esp32 dev board.

Is it possible to use `load` command? Thanks!

**Comment by igrr** [comment]
No, it's not possible to use 'load' with .bin files. Eventually it might be possible to use 'load' with elf files, but even that is tricky. This is because GDB reads load address from the elf file, and uses it to figure out how to load particular segment. For text/data segments located in RAM, GDB will write the data to RAM. But same doesn't work for segments which are mapped to cache. These need to be loaded by writing into correct locations in flash, and these locations are usually determined by other tools, such as esptool.py. So effectively OpenOCD would need to know about esp32 binary image format, and how to generate it. It's possible, but quite tricky and has lots of edge cases, so for now please use `mon program_esp32` instead.
