### ISSUE TITLE
Where can I found the interface file for ESP-Prog?

### ISSUE THREAD

**Issue by Super169** [espressif/openocd-esp32#55]
I just bought the ESP-Prog for debugging the ESP32 sketch.
I have followed the step here to config for JTAG Debugging (http://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/index.html#)

When I go to the step to Run OpenOCD, it need to provide the interface file, I can find some interface files in openocd\scripts\interface & openocd\scripts\interface\ftdi.

But I don't know which one is suitable for ESP-Prog, there does not have a cfg with the name like ESP-Prog.

Is ESP-Prog supported in OpenOCD?  If so, does anyone know where I can get the interface file for ESP-Prog,  or which of the existing interface file can be used?   

Thanks a lot!

**Comment by costaud** [comment]
Since the ESP-Prog is using the same chip(FT2232) as the one on WroverKit board, you can follow the instructions for [WROVER JTAG Interface](http://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/configure-wrover.html). 

The interface file should also be `interface/ftdi/esp32_devkitj_v1.cfg`
